import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className="h-[100vh] bg-[url('/bg.jpg')] bg-no-repeat bg-cover w-[100vw]">
				<div
					style={{ background: "rgba(0,0,0,0.6)" }}
					className="flex justify-center items-center absolute top-0 z-10 h-[100vh] w-[100vw]"
				>
					{children}
				</div>
			</body>
		</html>
	);
}
